### ISSUE TITLE
AttributeError: 'list' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by Gaoee** [uber-research/deep-neuroevolution#24]
When I run '. scripts/local_run_exp.sh es configurations/frostbite_es.json', I got such error 'AttributeError: 'list' object has no attribute 'ndim'' . 

Part of log:
'env_id': 'FrostbiteNoFrameskip-v4',
 'optimizer': {'args': {'stepsize': 0.01}, 'type': 'adam'},
 'policy': {'args': {}, 'type': 'ESAtariPolicy'}}
********** Iteration 0 **********
Traceback (most recent call last):
  File "/home/gaoli/tools/Python3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gaoli/tools/Python3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gaoli/CODE/deep-neuroevolution/es_distributed/main.py", line 90, in <module>
    cli()
  File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/gaoli/CODE/deep-neuroevolution/es_distributed/main.py", line 61, in master
    algo.run_master({'unix_socket_path': master_socket_path}, log_dir, exp)
  File "/home/gaoli/CODE/deep-neuroevolution/es_distributed/es.py", line 246, in run_master
    assert (result.noise_inds_n.ndim == 1 and
AttributeError: 'list' object has no attribute 'ndim'

**Comment by thisisjasleen** [comment]
Did you figure out the solution to this error? I have been facing the same issue!
